---
title: "DEPURACIÓN TICKETS"
author: "GRUPO C"
date: "2024-04-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, message=FALSE} 
#(package manager) para gestionar la instalación de librerías. 
#message=FALSE no sale cuando se compila
# Asegúrate que el paquete "pacman" está instalado
if (!require("pacman")) install.packages("pacman")

#Utilizamos la función `p_load` para la carga e instalación de paquetes
p_load(ggplot2, knitr, tidyverse,stringr,lubridate, png , reticulate)

rm(list = ls())
```

```{r,echo=FALSE,warning=FALSE,message=FALSE}
list_tickets <- list.files("data", pattern = "\\.txt$", full.names = TRUE)

ticket <- readLines(list_tickets[1])

for (i in ticket){

  ticket <- iconv(ticket, "latin1", "ASCII", sub = "")
  ticket <- gsub("Ñ","N",ticket)
  
}

ticket <- as.data.frame(ticket)
len_ticket <- as.numeric(nrow(ticket))
supermercado <- ticket[1,]
direccion <- ticket[2,]
codigo_postal_ciudad <- ticket[3,]
telefono <- ticket[4,]
fecha_hora_operador <- ticket[5,]
factura <- ticket[6,]
productos <- ticket[c(8:(len_ticket-14)),]
importe_total <- ticket[len_ticket-1,]
  
  ticket1.tidy <- data.frame( supermercado, direccion, codigo_postal_ciudad,
                             telefono, fecha_hora_operador, factura, productos,
                             importe_total)
  
```

```{r}
  
ticket <- readLines(list_tickets[2])

for (i in ticket){

  ticket <- iconv(ticket, "latin1", "ASCII", sub = "")
  ticket <- gsub("Ñ","N",ticket)
  
}
ticket <- as.data.frame(ticket)
len_ticket <- as.numeric(nrow(ticket))
supermercado <- ticket[1,]
direccion <- ticket[2,]
codigo_postal_ciudad <- ticket[3,]
telefono <- ticket[4,]
fecha_hora_operador <- ticket[5,]
factura <- ticket[6,]
productos <- ticket[c(8:(len_ticket-17)),]
importe_total <- ticket[len_ticket-3,]
  
ticket2.tidy <- data.frame(supermercado, direccion, codigo_postal_ciudad,
                             telefono, fecha_hora_operador, factura, productos,
                             importe_total)
  
ticket <- readLines(list_tickets[3])

for (i in ticket){

  ticket <- iconv(ticket, "latin1", "ASCII", sub = "")
  ticket <- gsub("Ñ","N",ticket)
  
}
ticket <- as.data.frame(ticket)
len_ticket <- as.numeric(nrow(ticket))
supermercado <- ticket[1,]
direccion <- ticket[2,]
codigo_postal_ciudad <- ticket[3,]
telefono <- ticket[4,]
fecha_hora_operador <- ticket[5,]
factura <- ticket[6,]
productos <- ticket[c(8:(len_ticket-15)),]
importe_total <- ticket[len_ticket-1,]
  
ticket3.tidy <- data.frame(supermercado, direccion, codigo_postal_ciudad,
                             telefono, fecha_hora_operador, factura, productos,
                             importe_total)

ticket <- readLines(list_tickets[4])

for (i in ticket){

  ticket <- iconv(ticket, "latin1", "ASCII", sub = "")
  ticket <- gsub("Ñ","N",ticket)
  
}
ticket <- as.data.frame(ticket)
len_ticket <- as.numeric(nrow(ticket))
supermercado <- ticket[1,]
direccion <- ticket[2,]
codigo_postal_ciudad <- ticket[3,]
telefono <- ticket[4,]
fecha_hora_operador <- ticket[5,]
factura <- ticket[6,]
productos <- ticket[c(8:(len_ticket-14)),]
importe_total <- ticket[len_ticket-1,]
  
ticket4.tidy <- data.frame(supermercado, direccion, codigo_postal_ciudad,
                             telefono, fecha_hora_operador, factura, productos,
                             importe_total)

ticket <- readLines(list_tickets[5])

for (i in ticket){

  ticket <- iconv(ticket, "latin1", "ASCII", sub = "")
  ticket <- gsub("Ñ","N",ticket)
  
}
ticket <- as.data.frame(ticket)
len_ticket <- as.numeric(nrow(ticket))
supermercado <- ticket[1,]
direccion <- ticket[2,]
codigo_postal_ciudad <- ticket[3,]
telefono <- ticket[4,]
fecha_hora_operador <- ticket[5,]
factura <- ticket[6,]
productos <- ticket[c(8:(len_ticket-15)),]
importe_total <- ticket[len_ticket-1,]
  
ticket5.tidy <- data.frame(supermercado, direccion, codigo_postal_ciudad,
                             telefono, fecha_hora_operador, factura, productos,
                             importe_total)

ticket <- readLines(list_tickets[6])

for (i in ticket){

  ticket <- iconv(ticket, "latin1", "ASCII", sub = "")
  ticket <- gsub("Ñ","N",ticket)
  
}
ticket <- as.data.frame(ticket)
len_ticket <- as.numeric(nrow(ticket))
supermercado <- ticket[1,]
direccion <- ticket[2,]
codigo_postal_ciudad <- ticket[3,]
telefono <- ticket[4,]
fecha_hora_operador <- ticket[5,]
factura <- ticket[6,]
productos <- ticket[c(8:(len_ticket-15)),]
importe_total <- ticket[len_ticket-1,]
  
ticket6.tidy <- data.frame(supermercado, direccion, codigo_postal_ciudad,
                             telefono, fecha_hora_operador, factura, productos,
                             importe_total)

ticket <- readLines(list_tickets[7])

for (i in ticket){

  ticket <- iconv(ticket, "latin1", "ASCII", sub = "")
  ticket <- gsub("Ñ","N",ticket)
  
}
ticket <- as.data.frame(ticket)
len_ticket <- as.numeric(nrow(ticket))
supermercado <- ticket[1,]
direccion <- ticket[2,]
codigo_postal_ciudad <- ticket[3,]
telefono <- ticket[4,]
fecha_hora_operador <- ticket[5,]
factura <- ticket[6,]
productos <- ticket[c(8:(len_ticket-14)),]
importe_total <- ticket[len_ticket-1,]
  
ticket7.tidy <- data.frame(supermercado, direccion, codigo_postal_ciudad,
                             telefono, fecha_hora_operador, factura, productos,
                             importe_total)

ticket <- readLines(list_tickets[8])

for (i in ticket){

  ticket <- iconv(ticket, "latin1", "ASCII", sub = "")
  ticket <- gsub("Ñ","N",ticket)
  
}
ticket <- as.data.frame(ticket)
len_ticket <- as.numeric(nrow(ticket))
supermercado <- ticket[1,]
direccion <- ticket[2,]
codigo_postal_ciudad <- ticket[3,]
telefono <- ticket[4,]
fecha_hora_operador <- ticket[5,]
factura <- ticket[6,]
productos <- ticket[c(8:(len_ticket-14)),]
importe_total <- ticket[len_ticket-1,]
  
ticket8.tidy <- data.frame(supermercado, direccion, codigo_postal_ciudad,
                             telefono, fecha_hora_operador, factura, productos,
                             importe_total)

ticket <- readLines(list_tickets[9])

for (i in ticket){

  ticket <- iconv(ticket, "latin1", "ASCII", sub = "")
  ticket <- gsub("Ñ","N",ticket)
  
}
ticket <- as.data.frame(ticket)
len_ticket <- as.numeric(nrow(ticket))
supermercado <- ticket[1,]
direccion <- ticket[2,]
codigo_postal_ciudad <- ticket[3,]
telefono <- ticket[4,]
fecha_hora_operador <- ticket[5,]
factura <- ticket[6,]
productos <- ticket[c(8:(len_ticket-15)),]
importe_total <- ticket[len_ticket-1,]
  
ticket9.tidy <- data.frame(supermercado, direccion, codigo_postal_ciudad,
                             telefono, fecha_hora_operador, factura, productos,
                             importe_total)

ticket <- readLines(list_tickets[10])

for (i in ticket){

  ticket <- iconv(ticket, "latin1", "ASCII", sub = "")
  ticket <- gsub("Ñ","N",ticket)
  
}
ticket <- as.data.frame(ticket)
len_ticket <- as.numeric(nrow(ticket))
supermercado <- ticket[1,]
direccion <- ticket[2,]
codigo_postal_ciudad <- ticket[3,]
telefono <- ticket[4,]
fecha_hora_operador <- ticket[5,]
factura <- ticket[6,]
productos <- ticket[c(8:(len_ticket-14)),]
importe_total <- ticket[len_ticket-1,]
  
ticket10.tidy <- data.frame(supermercado, direccion, codigo_postal_ciudad,
                             telefono, fecha_hora_operador, factura, productos,
                             importe_total)

ticket <- readLines(list_tickets[11])

for (i in ticket){

  ticket <- iconv(ticket, "latin1", "ASCII", sub = "")
  ticket <- gsub("Ñ","N",ticket)
  
}
ticket <- as.data.frame(ticket)
len_ticket <- as.numeric(nrow(ticket))
supermercado <- ticket[1,]
direccion <- ticket[2,]
codigo_postal_ciudad <- ticket[3,]
telefono <- ticket[4,]
fecha_hora_operador <- ticket[5,]
factura <- ticket[6,]
productos <- ticket[c(8:(len_ticket-17)),]
importe_total <- ticket[len_ticket-3,]
  
ticket11.tidy <- data.frame(supermercado, direccion, codigo_postal_ciudad,
                             telefono, fecha_hora_operador, factura, productos, 
                             importe_total)

ticket <- readLines(list_tickets[12])

for (i in ticket){

  ticket <- iconv(ticket, "latin1", "ASCII", sub = "")
  ticket <- gsub("Ñ","N",ticket)
  
}
ticket <- as.data.frame(ticket)
len_ticket <- as.numeric(nrow(ticket))
supermercado <- ticket[1,]
direccion <- ticket[2,]
codigo_postal_ciudad <- ticket[3,]
telefono <- ticket[4,]
fecha_hora_operador <- ticket[5,]
factura <- ticket[6,]
productos <- ticket[c(8:(len_ticket-17)),]
importe_total <- ticket[len_ticket-3,]
  
ticket12.tidy <- data.frame(supermercado, direccion, codigo_postal_ciudad,
                             telefono, fecha_hora_operador, factura, productos,
                             importe_total)

ticket <- readLines(list_tickets[13])

for (i in ticket){

  ticket <- iconv(ticket, "latin1", "ASCII", sub = "")
  ticket <- gsub("Ñ","N",ticket)
  
}
ticket <- as.data.frame(ticket)
len_ticket <- as.numeric(nrow(ticket))
supermercado <- ticket[1,]
direccion <- ticket[2,]
codigo_postal_ciudad <- ticket[3,]
telefono <- ticket[4,]
fecha_hora_operador <- ticket[5,]
factura <- ticket[6,]
productos <- ticket[c(8:(len_ticket-17)),]
importe_total <- ticket[len_ticket-3,]
  
ticket13.tidy <- data.frame(supermercado, direccion, codigo_postal_ciudad,
                             telefono, fecha_hora_operador, factura, productos,
                             importe_total)

ticket <- readLines(list_tickets[14])

for (i in ticket){

  ticket <- iconv(ticket, "latin1", "ASCII", sub = "")
  ticket <- gsub("Ñ","N",ticket)
  
}
ticket <- as.data.frame(ticket)
len_ticket <- as.numeric(nrow(ticket))
supermercado <- ticket[1,]
direccion <- ticket[2,]
codigo_postal_ciudad <- ticket[3,]
telefono <- ticket[4,]
fecha_hora_operador <- ticket[5,]
factura <- ticket[6,]
productos <- ticket[c(8:(len_ticket-14)),]
importe_total <- ticket[len_ticket-1,]
  
ticket14.tidy <- data.frame(supermercado, direccion, codigo_postal_ciudad,
                             telefono, fecha_hora_operador, factura, productos,
                             importe_total)

ticket <- readLines(list_tickets[15])

for (i in ticket){

  ticket <- iconv(ticket, "latin1", "ASCII", sub = "")
  ticket <- gsub("Ñ","N",ticket)
  
}
ticket <- as.data.frame(ticket)
len_ticket <- as.numeric(nrow(ticket))
supermercado <- ticket[1,]
direccion <- ticket[2,]
codigo_postal_ciudad <- ticket[3,]
telefono <- ticket[4,]
fecha_hora_operador <- ticket[5,]
factura <- ticket[6,]
productos <- ticket[c(8:(len_ticket-16)),]
importe_total <- ticket[len_ticket-3,]
  
ticket15.tidy <- data.frame(supermercado, direccion, codigo_postal_ciudad,
                             telefono, fecha_hora_operador, factura, productos,
                             importe_total)

ticket <- readLines(list_tickets[16])

for (i in ticket){

  ticket <- iconv(ticket, "latin1", "ASCII", sub = "")
  ticket <- gsub("Ñ","N",ticket)
  
}
ticket <- as.data.frame(ticket)
len_ticket <- as.numeric(nrow(ticket))
supermercado <- ticket[1,]
direccion <- ticket[2,]
codigo_postal_ciudad <- ticket[3,]
telefono <- ticket[4,]
fecha_hora_operador <- ticket[5,]
factura <- ticket[6,]
productos <- ticket[c(8:(len_ticket-17)),]
importe_total <- ticket[len_ticket-3,]
  
ticket16.tidy <- data.frame(supermercado, direccion, codigo_postal_ciudad,
                             telefono, fecha_hora_operador, factura, productos,
                             importe_total)

ticket <- readLines(list_tickets[17])

for (i in ticket){

  ticket <- iconv(ticket, "latin1", "ASCII", sub = "")
  ticket <- gsub("Ñ","N",ticket)
  
}
ticket <- as.data.frame(ticket)
len_ticket <- as.numeric(nrow(ticket))
supermercado <- ticket[1,]
direccion <- ticket[2,]
codigo_postal_ciudad <- ticket[3,]
telefono <- ticket[4,]
fecha_hora_operador <- ticket[5,]
factura <- ticket[6,]
productos <- ticket[c(8:(len_ticket-14)),]
importe_total <- ticket[len_ticket-1,]

ticket17.tidy <- data.frame(supermercado, direccion, codigo_postal_ciudad,
                             telefono, fecha_hora_operador, factura, productos,
                             importe_total)
```

```{r}
ticket1.tidy$telefono <- gsub("[[:alpha:]]", "",ticket1.tidy$telefono)

ticket1.tidy$fecha_hora_operador <- gsub("  OP: [0123456789]*","",ticket1.tidy$fecha_hora_operador)

ticket1.tidy <- ticket1.tidy |> separate(col = fecha_hora_operador, 
                                         into = c("Fecha","Hora"),sep = " ")

ticket1.tidy$Fecha <- dmy(ticket1.tidy$Fecha)

ticket1.tidy$Hora <- hm(ticket1.tidy$Hora)

ticket1.tidy$importe_total <- gsub("[[:alpha:]]", "", ticket1.tidy$importe_total)

ticket1.tidy$importe_total <- gsub(" ", "", ticket1.tidy$importe_total)

ticket1.tidy$importe_total <- gsub(",",".", ticket1.tidy$importe_total)

ticket1.tidy$importe_total <- gsub(":","",ticket1.tidy$importe_total)



ticket2.tidy$telefono <- gsub("[[:alpha:]]", "",ticket2.tidy$telefono)

ticket2.tidy$fecha_hora_operador <- gsub("  OP: [0123456789]*","",ticket2.tidy$fecha_hora_operador)

ticket2.tidy <- ticket2.tidy |> separate(col = fecha_hora_operador, 
                                         into = c("Fecha","Hora"),sep = " ")

ticket2.tidy$Fecha <- dmy(ticket2.tidy$Fecha)

ticket2.tidy$Hora <- hm(ticket2.tidy$Hora)

ticket2.tidy$importe_total <- gsub("[[:alpha:]]", "", ticket2.tidy$importe_total)

ticket2.tidy$importe_total <- gsub(" ", "", ticket2.tidy$importe_total)

ticket2.tidy$importe_total <- gsub(",",".", ticket2.tidy$importe_total)

ticket2.tidy$importe_total <- gsub(":","",ticket2.tidy$importe_total)



ticket3.tidy$telefono <- gsub("[[:alpha:]]", "",ticket3.tidy$telefono)

ticket3.tidy$fecha_hora_operador <- gsub("  OP: [0123456789]*","",ticket3.tidy$fecha_hora_operador)

ticket3.tidy <- ticket3.tidy |> separate(col = fecha_hora_operador, 
                                         into = c("Fecha","Hora"),sep = " ")

ticket3.tidy$Fecha <- dmy(ticket3.tidy$Fecha)

ticket3.tidy$Hora <- hm(ticket3.tidy$Hora)

ticket3.tidy$importe_total <- gsub("[[:alpha:]]", "", ticket3.tidy$importe_total)

ticket3.tidy$importe_total <- gsub(" ", "", ticket3.tidy$importe_total)

ticket3.tidy$importe_total <- gsub(",",".", ticket3.tidy$importe_total)

ticket3.tidy$importe_total <- gsub(":","",ticket3.tidy$importe_total)



ticket4.tidy$telefono <- gsub("[[:alpha:]]", "",ticket4.tidy$telefono)

ticket4.tidy$fecha_hora_operador <- gsub("  OP: [0123456789]*","",ticket4.tidy$fecha_hora_operador)

ticket4.tidy <- ticket4.tidy |> separate(col = fecha_hora_operador, 
                                         into = c("Fecha","Hora"),sep = " ")

ticket4.tidy$Fecha <- dmy(ticket4.tidy$Fecha)

ticket4.tidy$Hora <- hm(ticket4.tidy$Hora)

ticket4.tidy$importe_total <- gsub("[[:alpha:]]", "", ticket4.tidy$importe_total)

ticket4.tidy$importe_total <- gsub(" ", "", ticket4.tidy$importe_total)

ticket4.tidy$importe_total <- gsub(",",".", ticket4.tidy$importe_total)

ticket4.tidy$importe_total <- gsub(":","",ticket4.tidy$importe_total)



ticket5.tidy$telefono <- gsub("[[:alpha:]]", "",ticket5.tidy$telefono)

ticket5.tidy$fecha_hora_operador <- gsub("  OP: [0123456789]*","",ticket5.tidy$fecha_hora_operador)

ticket5.tidy <- ticket5.tidy |> separate(col = fecha_hora_operador, 
                                         into = c("Fecha","Hora"),sep = " ")

ticket5.tidy$Fecha <- dmy(ticket5.tidy$Fecha)

ticket5.tidy$Hora <- hm(ticket5.tidy$Hora)

ticket5.tidy$importe_total <- gsub("[[:alpha:]]", "", ticket5.tidy$importe_total)

ticket5.tidy$importe_total <- gsub(" ", "", ticket5.tidy$importe_total)

ticket5.tidy$importe_total <- gsub(",",".", ticket5.tidy$importe_total)

ticket5.tidy$importe_total <- gsub(":","",ticket5.tidy$importe_total)



ticket6.tidy$telefono <- gsub("[[:alpha:]]", "",ticket6.tidy$telefono)

ticket6.tidy$fecha_hora_operador <- gsub("  OP: [0123456789]*","",ticket6.tidy$fecha_hora_operador)

ticket6.tidy <- ticket6.tidy |> separate(col = fecha_hora_operador, 
                                         into = c("Fecha","Hora"),sep = " ")

ticket6.tidy$Fecha <- dmy(ticket6.tidy$Fecha)

ticket6.tidy$Hora <- hm(ticket6.tidy$Hora)

ticket6.tidy$importe_total <- gsub("[[:alpha:]]", "", ticket6.tidy$importe_total)

ticket6.tidy$importe_total <- gsub(" ", "", ticket6.tidy$importe_total)

ticket6.tidy$importe_total <- gsub(",",".", ticket6.tidy$importe_total)

ticket6.tidy$importe_total <- gsub(":","",ticket6.tidy$importe_total)



ticket7.tidy$telefono <- gsub("[[:alpha:]]", "",ticket7.tidy$telefono)

ticket7.tidy$fecha_hora_operador <- gsub("  OP: [0123456789]*","",ticket7.tidy$fecha_hora_operador)

ticket7.tidy <- ticket7.tidy |> separate(col = fecha_hora_operador, 
                                         into = c("Fecha","Hora"),sep = " ")

ticket7.tidy$Fecha <- dmy(ticket7.tidy$Fecha)

ticket7.tidy$Hora <- hm(ticket7.tidy$Hora)

ticket7.tidy$importe_total <- gsub("[[:alpha:]]", "", ticket7.tidy$importe_total)

ticket7.tidy$importe_total <- gsub(" ", "", ticket7.tidy$importe_total)

ticket7.tidy$importe_total <- gsub(",",".", ticket7.tidy$importe_total)

ticket7.tidy$importe_total <- gsub(":","",ticket7.tidy$importe_total)



ticket8.tidy$telefono <- gsub("[[:alpha:]]", "",ticket8.tidy$telefono)

ticket8.tidy$fecha_hora_operador <- gsub("  OP: [0123456789]*","",ticket8.tidy$fecha_hora_operador)

ticket8.tidy <- ticket8.tidy |> separate(col = fecha_hora_operador, 
                                         into = c("Fecha","Hora"),sep = " ")

ticket8.tidy$Fecha <- dmy(ticket8.tidy$Fecha)

ticket8.tidy$Hora <- hm(ticket8.tidy$Hora)

ticket8.tidy$importe_total <- gsub("[[:alpha:]]", "", ticket8.tidy$importe_total)

ticket8.tidy$importe_total <- gsub(" ", "", ticket8.tidy$importe_total)

ticket8.tidy$importe_total <- gsub(",",".", ticket8.tidy$importe_total)

ticket8.tidy$importe_total <- gsub(":","",ticket8.tidy$importe_total)



ticket9.tidy$telefono <- gsub("[[:alpha:]]", "",ticket9.tidy$telefono)

ticket9.tidy$fecha_hora_operador <- gsub("  OP: [0123456789]*","",ticket9.tidy$fecha_hora_operador)

ticket9.tidy <- ticket9.tidy |> separate(col = fecha_hora_operador, 
                                         into = c("Fecha","Hora"),sep = " ")

ticket9.tidy$Fecha <- dmy(ticket9.tidy$Fecha)

ticket9.tidy$Hora <- hm(ticket9.tidy$Hora)

ticket9.tidy$importe_total <- gsub("[[:alpha:]]", "", ticket9.tidy$importe_total)

ticket9.tidy$importe_total <- gsub(" ", "", ticket9.tidy$importe_total)

ticket9.tidy$importe_total <- gsub(",",".", ticket9.tidy$importe_total)

ticket9.tidy$importe_total <- gsub(":","",ticket9.tidy$importe_total)



ticket10.tidy$telefono <- gsub("[[:alpha:]]", "",ticket10.tidy$telefono)

ticket10.tidy$fecha_hora_operador <- gsub("  OP: [0123456789]*","",ticket10.tidy$fecha_hora_operador)

ticket10.tidy <- ticket10.tidy |> separate(col = fecha_hora_operador, 
                                         into = c("Fecha","Hora"),sep = " ")

ticket10.tidy$Fecha <- dmy(ticket10.tidy$Fecha)

ticket10.tidy$Hora <- hm(ticket10.tidy$Hora)

ticket10.tidy$importe_total <- gsub("[[:alpha:]]", "", ticket10.tidy$importe_total)

ticket10.tidy$importe_total <- gsub(" ", "", ticket10.tidy$importe_total)

ticket10.tidy$importe_total <- gsub(",",".", ticket10.tidy$importe_total)

ticket10.tidy$importe_total <- gsub(":","",ticket10.tidy$importe_total)



ticket11.tidy$telefono <- gsub("[[:alpha:]]", "",ticket11.tidy$telefono)

ticket11.tidy$fecha_hora_operador <- gsub("  OP: [0123456789]*","",ticket11.tidy$fecha_hora_operador)

ticket11.tidy <- ticket11.tidy |> separate(col = fecha_hora_operador, 
                                         into = c("Fecha","Hora"),sep = " ")

ticket11.tidy$Fecha <- dmy(ticket11.tidy$Fecha)

ticket11.tidy$Hora <- hm(ticket11.tidy$Hora)

ticket11.tidy$importe_total <- gsub("[[:alpha:]]", "", ticket11.tidy$importe_total)

ticket11.tidy$importe_total <- gsub(" ", "", ticket11.tidy$importe_total)

ticket11.tidy$importe_total <- gsub(",",".", ticket11.tidy$importe_total)

ticket11.tidy$importe_total <- gsub(":","",ticket11.tidy$importe_total)



ticket12.tidy$telefono <- gsub("[[:alpha:]]", "",ticket12.tidy$telefono)

ticket12.tidy$fecha_hora_operador <- gsub("  OP: [0123456789]*","",ticket12.tidy$fecha_hora_operador)

ticket12.tidy <- ticket12.tidy |> separate(col = fecha_hora_operador, 
                                         into = c("Fecha","Hora"),sep = " ")

ticket12.tidy$Fecha <- dmy(ticket12.tidy$Fecha)

ticket12.tidy$Hora <- hm(ticket12.tidy$Hora)

ticket12.tidy$importe_total <- gsub("[[:alpha:]]", "", ticket12.tidy$importe_total)

ticket12.tidy$importe_total <- gsub(" ", "", ticket12.tidy$importe_total)

ticket12.tidy$importe_total <- gsub(",",".", ticket12.tidy$importe_total)

ticket12.tidy$importe_total <- gsub(":","",ticket12.tidy$importe_total)



ticket13.tidy$telefono <- gsub("[[:alpha:]]", "",ticket13.tidy$telefono)

ticket13.tidy$fecha_hora_operador <- gsub("  OP: [0123456789]*","",ticket13.tidy$fecha_hora_operador)

ticket13.tidy <- ticket13.tidy |> separate(col = fecha_hora_operador, 
                                         into = c("Fecha","Hora"),sep = " ")

ticket13.tidy$Fecha <- dmy(ticket13.tidy$Fecha)

ticket13.tidy$Hora <- hm(ticket13.tidy$Hora)

ticket13.tidy$importe_total <- gsub("[[:alpha:]]", "", ticket13.tidy$importe_total)

ticket13.tidy$importe_total <- gsub(" ", "", ticket13.tidy$importe_total)

ticket13.tidy$importe_total <- gsub(",",".", ticket13.tidy$importe_total)

ticket13.tidy$importe_total <- gsub(":","",ticket13.tidy$importe_total)



ticket14.tidy$telefono <- gsub("[[:alpha:]]", "",ticket14.tidy$telefono)

ticket14.tidy$fecha_hora_operador <- gsub("  OP: [0123456789]*","",ticket14.tidy$fecha_hora_operador)

ticket14.tidy <- ticket14.tidy |> separate(col = fecha_hora_operador, 
                                         into = c("Fecha","Hora"),sep = " ")

ticket14.tidy$Fecha <- dmy(ticket14.tidy$Fecha)

ticket14.tidy$Hora <- hm(ticket14.tidy$Hora)

ticket14.tidy$importe_total <- gsub("[[:alpha:]]", "", ticket14.tidy$importe_total)

ticket14.tidy$importe_total <- gsub(" ", "", ticket14.tidy$importe_total)

ticket14.tidy$importe_total <- gsub(",",".", ticket14.tidy$importe_total)

ticket14.tidy$importe_total <- gsub(":","",ticket14.tidy$importe_total)



ticket15.tidy$telefono <- gsub("[[:alpha:]]", "",ticket15.tidy$telefono)

ticket15.tidy$fecha_hora_operador <- gsub("  OP: [0123456789]*","",ticket15.tidy$fecha_hora_operador)

ticket15.tidy <- ticket15.tidy |> separate(col = fecha_hora_operador, 
                                         into = c("Fecha","Hora"),sep = " ")

ticket15.tidy$Fecha <- dmy(ticket15.tidy$Fecha)

ticket15.tidy$Hora <- hm(ticket15.tidy$Hora)

ticket15.tidy$importe_total <- gsub("[[:alpha:]]", "", ticket15.tidy$importe_total)

ticket15.tidy$importe_total <- gsub(" ", "", ticket15.tidy$importe_total)

ticket15.tidy$importe_total <- gsub(",",".", ticket15.tidy$importe_total)

ticket15.tidy$importe_total <- gsub(":","",ticket15.tidy$importe_total)



ticket16.tidy$telefono <- gsub("[[:alpha:]]", "",ticket16.tidy$telefono)

ticket16.tidy$fecha_hora_operador <- gsub("  OP: [0123456789]*","",ticket16.tidy$fecha_hora_operador)

ticket16.tidy <- ticket16.tidy |> separate(col = fecha_hora_operador, 
                                         into = c("Fecha","Hora"),sep = " ")

ticket16.tidy$Fecha <- dmy(ticket16.tidy$Fecha)

ticket16.tidy$Hora <- hm(ticket16.tidy$Hora)

ticket16.tidy$importe_total <- gsub("[[:alpha:]]", "", ticket16.tidy$importe_total)

ticket16.tidy$importe_total <- gsub(" ", "", ticket16.tidy$importe_total)

ticket16.tidy$importe_total <- gsub(",",".", ticket16.tidy$importe_total)

ticket16.tidy$importe_total <- gsub(":","",ticket16.tidy$importe_total)



ticket17.tidy$telefono <- gsub("[[:alpha:]]", "",ticket17.tidy$telefono)

ticket17.tidy$fecha_hora_operador <- gsub("  OP: [0123456789]*","",ticket17.tidy$fecha_hora_operador)

ticket17.tidy <- ticket17.tidy |> separate(col = fecha_hora_operador, 
                                         into = c("Fecha","Hora"),sep = " ")

ticket17.tidy$Fecha <- dmy(ticket17.tidy$Fecha)

ticket17.tidy$Hora <- hm(ticket17.tidy$Hora)

ticket17.tidy$importe_total <- gsub("[[:alpha:]]", "", ticket17.tidy$importe_total)

ticket17.tidy$importe_total <- gsub(" ", "", ticket17.tidy$importe_total)

ticket17.tidy$importe_total <- gsub(",",".", ticket17.tidy$importe_total)

ticket17.tidy$importe_total <- gsub(":","",ticket17.tidy$importe_total)
```

```{r}
fechas <- c(ticket1.tidy$Fecha,ticket2.tidy$Fecha,ticket3.tidy$Fecha,
            ticket4.tidy$Fecha,ticket5.tidy$Fecha,ticket6.tidy$Fecha,
            ticket7.tidy$Fecha,ticket8.tidy$Fecha,ticket9.tidy$Fecha,
            ticket10.tidy$Fecha,ticket11.tidy$Fecha,ticket12.tidy$Fecha,
            ticket13.tidy$Fecha,ticket14.tidy$Fecha,ticket15.tidy$Fecha,
            ticket16.tidy$Fecha,ticket17.tidy$Fecha)

fechas <- unique(fechas)

fechas <- c(wday(fechas[1],label=TRUE),wday(fechas[2],label = TRUE),
            wday(fechas[3],label = TRUE),wday(fechas[4],label = TRUE),
            wday(fechas[5],label = TRUE),wday(fechas[6],label = TRUE),
            wday(fechas[17],label = TRUE),wday(fechas[8],label = TRUE),
            wday(fechas[9],label = TRUE),wday(fechas[10],label = TRUE),
            wday(fechas[11],label = TRUE),wday(fechas[12],label = TRUE),
            wday(fechas[13],label = TRUE),wday(fechas[14],label = TRUE),
            wday(fechas[15],label = TRUE),wday(fechas[16],label = TRUE),
            wday(fechas[17],label = TRUE))
```

```{r}
Productos <- c(ticket1.tidy$productos, ticket2.tidy$productos,
                     ticket3.tidy$productos,ticket4.tidy$productos,
                     ticket5.tidy$productos,ticket6.tidy$productos,
                     ticket7.tidy$productos,ticket8.tidy$productos,
                     ticket9.tidy$productos,ticket10.tidy$productos,
                     ticket11.tidy$productos,ticket12.tidy$productos,
                     ticket13.tidy$productos,ticket14.tidy$productos,
                     ticket15.tidy$productos,ticket16.tidy$productos,
                     ticket17.tidy$productos)

Precios <- Productos

todos_productos <- data.frame(Productos,Precios)
```

```{r}
todos_productos$Productos <- gsub("[[:digit:]]","",todos_productos$Productos)

todos_productos$Productos <- gsub("[[:punct:]]","",todos_productos$Productos)

todos_productos$Productos <- gsub("kg",NA,todos_productos$Productos)

productos_dep <- unique(todos_productos$Productos)

pesos <- which(is.na(todos_productos$Productos))
```

```{r}
todos_productos[pesos[1]-1,2] <- todos_productos[pesos[1],2]
todos_productos[pesos[2]-1,2] <- todos_productos[pesos[2],2]
todos_productos[pesos[3]-1,2] <- todos_productos[pesos[3],2]
todos_productos[pesos[4]-1,2] <- todos_productos[pesos[4],2]
todos_productos[pesos[5]-1,2] <- todos_productos[pesos[5],2]
todos_productos[pesos[6]-1,2] <- todos_productos[pesos[6],2]
todos_productos[pesos[7]-1,2] <- todos_productos[pesos[7],2]
todos_productos[pesos[8]-1,2] <- todos_productos[pesos[8],2]
todos_productos[pesos[9]-1,2] <- todos_productos[pesos[9],2]
todos_productos[pesos[10]-1,2] <- todos_productos[pesos[10],2]
todos_productos[pesos[11]-1,2] <- todos_productos[pesos[11],2]
todos_productos[pesos[12]-1,2] <- todos_productos[pesos[12],2]
todos_productos[pesos[13]-1,2] <- todos_productos[pesos[13],2]
todos_productos[pesos[14]-1,2] <- todos_productos[pesos[14],2]
todos_productos[pesos[15]-1,2] <- todos_productos[pesos[15],2]
todos_productos[pesos[16]-1,2] <- todos_productos[pesos[16],2]
todos_productos[pesos[17]-1,2] <- todos_productos[pesos[17],2]

todos_productos[pesos[1],2] <- NA
todos_productos[pesos[2],2] <- NA
todos_productos[pesos[3],2] <- NA
todos_productos[pesos[4],2] <- NA
todos_productos[pesos[5],2] <- NA
todos_productos[pesos[6],2] <- NA
todos_productos[pesos[7],2] <- NA
todos_productos[pesos[8],2] <- NA
todos_productos[pesos[9],2] <- NA
todos_productos[pesos[10],2] <- NA
todos_productos[pesos[11],2] <- NA
todos_productos[pesos[12],2] <- NA
todos_productos[pesos[13],2] <- NA
todos_productos[pesos[14],2] <- NA
todos_productos[pesos[15],2] <- NA
todos_productos[pesos[16],2] <- NA
todos_productos[pesos[17],2] <- NA
todos_productos[268,2] <- NA
todos_productos[135,2] <- NA

```

```{r}
pesos[1] <- pesos[1]-1
pesos[2] <- pesos[2]-1
pesos[3] <- pesos[3]-1
pesos[4] <- pesos[4]-1
pesos[5] <- pesos[5]-1
pesos[6] <- pesos[6]-1
pesos[7] <- pesos[7]-1
pesos[8] <- pesos[8]-1
pesos[9] <- pesos[9]-1
pesos[10] <- pesos[10]-1
pesos[11] <- pesos[11]-1
pesos[12] <- pesos[12]-1
pesos[13] <- pesos[13]-1
pesos[14] <- pesos[14]-1
pesos[15] <- pesos[15]-1
pesos[16] <- pesos[16]-1
pesos[17] <- pesos[17]-1

todos_productos$Precios <- gsub("^.","",todos_productos$Precios)

todos_productos$Precios <- gsub("[[:alpha:]]","", todos_productos$Precios)

todos_productos <- na.omit(todos_productos)

for (n in c(1:nrow(todos_productos))){
  
  a <- strsplit(todos_productos[n,2], " ")[[1]]
  
  todos_productos[n,2] <- a[length(a)]
  
}
```


```{r}
todos_productos$Productos <- as.factor(todos_productos$Productos)

table(todos_productos$Productos)
```


